package vibescore

import (
	"time"
)

// EvaluationDimension represents a single quality dimension score
type EvaluationDimension struct {
	Score      float64 `json:"score"`      // 0-10 scale
	Feedback   string  `json:"feedback"`   // Detailed feedback for this dimension
	Issues     []string `json:"issues,omitempty"`    // Specific issues found
	Strengths  []string `json:"strengths,omitempty"` // Positive aspects
}

// Status represents the evaluation result status
type Status string

const (
	StatusPass       Status = "pass"        // overall_score >= quality_threshold
	StatusFail       Status = "fail"        // overall_score < quality_threshold
	StatusNeedsReview Status = "needs_review" // Requires human review
)

// EvaluatorType represents which LLM evaluated the scorecard
type EvaluatorType string

const (
	EvaluatorClaude     EvaluatorType = "claude"
	EvaluatorGemini     EvaluatorType = "gemini"
	EvaluatorAntigravity EvaluatorType = "antigravity"
	EvaluatorCustom     EvaluatorType = "custom"
)

// VibeScoreCard represents a complete quality evaluation of a task result
type VibeScoreCard struct {
	// Primary Key
	ID string `json:"id" db:"id"`

	// Evaluation Scores (0-10 scale)
	Correctness     float64 `json:"correctness" db:"correctness"`           // Does it work correctly?
	Efficiency      float64 `json:"efficiency" db:"efficiency"`             // Is it performant?
	Maintainability float64 `json:"maintainability" db:"maintainability"`   // Is it clean and understandable?
	Security        float64 `json:"security" db:"security"`                 // Is it secure and safe?
	OverallScore    float64 `json:"overall_score" db:"overall_score"`       // Average of all dimensions

	// Task Reference
	TaskID string `json:"task_id" db:"task_id"` // Reference to the task being evaluated

	// Evaluator Information
	Evaluator      string `json:"evaluator" db:"evaluator"`           // "claude", "gemini", "antigravity", etc.
	EvaluatorModel string `json:"evaluator_model" db:"evaluator_model"` // e.g., "claude-opus-4-5", "gemini-2.5-pro"
	EvaluatedAt    time.Time `json:"evaluated_at" db:"evaluated_at"`     // When the evaluation occurred

	// Feedback for Each Dimension
	CorrectnessFeedback     string `json:"correctness_feedback" db:"correctness_feedback"`
	EfficiencyFeedback      string `json:"efficiency_feedback" db:"efficiency_feedback"`
	MaintainabilityFeedback string `json:"maintainability_feedback" db:"maintainability_feedback"`
	SecurityFeedback        string `json:"security_feedback" db:"security_feedback"`

	// Overall Assessment
	SummaryFeedback       string   `json:"summary_feedback" db:"summary_feedback"` // Concise overall summary
	ImprovementSuggestions []string `json:"improvement_suggestions" db:"improvement_suggestions"` // Array of suggestions

	// Pass/Fail Determination
	Status            Status  `json:"status" db:"status"` // "pass", "fail", "needs_review"
	QualityThreshold  float64 `json:"quality_threshold" db:"quality_threshold"` // Minimum score to pass (default: 6.0)

	// Retry Tracking
	RetryCount      int    `json:"retry_count" db:"retry_count"`         // Number of retries before this evaluation (0 = first attempt)
	PreviousScoreID string `json:"previous_score_id" db:"previous_score_id"` // ID of previous evaluation if retried

	// Additional Metadata
	Metadata map[string]interface{} `json:"metadata" db:"metadata"` // Custom metadata (language, complexity, etc.)

	// PocketBase fields
	Created time.Time `json:"created" db:"created"` // Auto-generated by PocketBase
	Updated time.Time `json:"updated" db:"updated"` // Auto-generated by PocketBase
}

// ScoreSummary provides a quick summary of evaluation results
type ScoreSummary struct {
	TaskID           string
	OverallScore     float64
	Status           Status
	EvaluatedAt      time.Time
	Evaluator        string
	DimensionScores  map[string]float64 // "correctness", "efficiency", "maintainability", "security"
}

// ScoreFilter is used for querying vibescore records
type ScoreFilter struct {
	TaskID           string
	Evaluator        string
	StatusFilter     Status
	MinScore         float64
	MaxScore         float64
	StartDate        time.Time
	EndDate          time.Time
	SortBy           string // "overall_score", "evaluated_at", etc.
	SortOrder        string // "asc", "desc"
	Limit            int
	Offset           int
}

// CalculateOverallScore computes the average of all four dimensions
func (v *VibeScoreCard) CalculateOverallScore() float64 {
	if v == nil {
		return 0.0
	}
	total := v.Correctness + v.Efficiency + v.Maintainability + v.Security
	return total / 4.0
}

// DetermineStatus sets the Status field based on OverallScore and QualityThreshold
func (v *VibeScoreCard) DetermineStatus() Status {
	if v == nil {
		return StatusNeedsReview
	}

	// Default threshold if not set
	threshold := v.QualityThreshold
	if threshold == 0 {
		threshold = 6.0
	}

	if v.OverallScore >= threshold {
		return StatusPass
	}
	return StatusFail
}

// IsPass returns true if status is Pass
func (v *VibeScoreCard) IsPass() bool {
	return v != nil && v.Status == StatusPass
}

// IsFail returns true if status is Fail
func (v *VibeScoreCard) IsFail() bool {
	return v != nil && v.Status == StatusFail
}

// NeedsReview returns true if status is NeedsReview
func (v *VibeScoreCard) NeedsReview() bool {
	return v != nil && v.Status == StatusNeedsReview
}

// HasIssues returns true if any dimension score is below 5.0 (mid-range)
func (v *VibeScoreCard) HasIssues() bool {
	if v == nil {
		return true
	}
	return v.Correctness < 5.0 || v.Efficiency < 5.0 ||
		v.Maintainability < 5.0 || v.Security < 5.0
}

// GetDimensionScores returns a map of all dimension scores
func (v *VibeScoreCard) GetDimensionScores() map[string]float64 {
	if v == nil {
		return make(map[string]float64)
	}
	return map[string]float64{
		"correctness":     v.Correctness,
		"efficiency":      v.Efficiency,
		"maintainability": v.Maintainability,
		"security":        v.Security,
	}
}

// GetFeedbackMap returns a map of all dimension feedback
func (v *VibeScoreCard) GetFeedbackMap() map[string]string {
	if v == nil {
		return make(map[string]string)
	}
	return map[string]string{
		"correctness":     v.CorrectnessFeedback,
		"efficiency":      v.EfficiencyFeedback,
		"maintainability": v.MaintainabilityFeedback,
		"security":        v.SecurityFeedback,
	}
}

// ToSummary converts the full scorecard to a concise summary
func (v *VibeScoreCard) ToSummary() ScoreSummary {
	if v == nil {
		return ScoreSummary{}
	}
	return ScoreSummary{
		TaskID:        v.TaskID,
		OverallScore:  v.OverallScore,
		Status:        v.Status,
		EvaluatedAt:   v.EvaluatedAt,
		Evaluator:     v.Evaluator,
		DimensionScores: v.GetDimensionScores(),
	}
}
